### ISSUE TITLE
How do you make this code work?

### ISSUE THREAD

**Issue by maoweipengft** [CoinSpace/CoinSpace#17]
How do you make this code work?

**Comment by daverod24** [comment]
good morning

I would like to know how I can run on my localhost the project

clone the git and then copy .env.example to .env.loc
DB_CONNECT =
DB_NAME =
COOKIE_SALT =
USERNAME_SALT =
NODE_ENV = development
PORT = 8080
SITE_URL = http: // localhost: 8000 / api /
API_BTC_URL = https: //btc.coin.space/api/
API_BCH_URL = https: //bch.coin.space/api/
API_LTC_URL = https: //ltc.coin.space/api/
API_ETH_URL = https: //eth.coin.space/api/v1/
API_XRP_URL = https: //xrp.coin.space/api/v1/
API_XLM_URL = https: //xlm.coin.space/api/v1/
IOS_APP_ID =
SHAPESHIFT_API_KEY =
ANDROID_BILLING_KEY =
GOOGLE_GTM =
IAP_APPLE_PASSWORD =
IAP_GOOGLE_PUBLIC_KEY =
 
then I did docker-compose up

but I would like to know the official documented process of you


Thanks in advance

we want to support

**Comment by lane-c-wagner** [comment]
I would also like to help. This is my error when using `docker-compose up`:

```
web_1         | (node:17) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
web_1         | error Error: Invalid schema, expected `mongodb` or `mongodb+srv`
web_1         |     at module.exports (/coin/node_modules/mongodb/lib/url_parser.js:21:21)
web_1         |     at deprecated (internal/util.js:67:15)
web_1         |     at connect (/coin/node_modules/mongodb/lib/operations/mongo_client_ops.js:180:3)
web_1         |     at connectOp (/coin/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
web_1         |     at /coin/node_modules/mongodb/lib/utils.js:437:24
web_1         |     at executeOperation (/coin/node_modules/mongodb/lib/utils.js:432:10)
web_1         |     at MongoClient.connect (/coin/node_modules/mongodb/lib/mongo_client.js:168:10)
web_1         |     at Function.MongoClient.connect (/coin/node_modules/mongodb/lib/mongo_client.js:372:22)
web_1         |     at module.exports (/coin/server/lib/v1/db.js:9:22)
web_1         |     at Object.<anonymous> (/coin/server/server.js:26:1)
web_master_1  | (node:17) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
web_master_1  | error Error: Invalid schema, expected `mongodb` or `mongodb+srv`
web_master_1  |     at module.exports (/coin/node_modules/mongodb/lib/url_parser.js:21:21)
web_master_1  |     at deprecated (internal/util.js:67:15)
web_master_1  |     at connect (/coin/node_modules/mongodb/lib/operations/mongo_client_ops.js:180:3)
web_master_1  |     at connectOp (/coin/node_modules/mongodb/lib/operations/mongo_client_ops.js:284:3)
web_master_1  |     at /coin/node_modules/mongodb/lib/utils.js:437:24
web_master_1  |     at executeOperation (/coin/node_modules/mongodb/lib/utils.js:432:10)
web_master_1  |     at MongoClient.connect (/coin/node_modules/mongodb/lib/mongo_client.js:168:10)
web_master_1  |     at Function.MongoClient.connect (/coin/node_modules/mongodb/lib/mongo_client.js:372:22)
web_master_1  |     at module.exports (/coin/server/lib/v1/db.js:9:22)
web_master_1  |     at Object.<anonymous> (/coin/server/server.js:26:1)
```

**Comment by dezzyboy** [comment]
no idea why there is no documentation on this but there seem to be steady commits just saying maybe you should try to respond to these minor issues
